sudo: required
services:
  - docker

before_install:
  - docker build -t samober/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run samober/react-test npm run test -- --coverage

after_success:
  # Build production containers
  - docker build -t samober/multi-docker-client ./client
  - docker build -t samober/multi-docker-nginx ./nginx
  - docker build -t samober/multi-docker-server ./server
  - docker build -t samober/multi-docker-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push all images to docker hub
  - docker push samober/multi-docker-client
  - docker push samober/multi-docker-nginx
  - docker push samober/multi-docker-server
  - docker push samober/multi-docker-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-127203601047'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
